package com.desalvo.mtaaudioeditor.mobile;
import android.content.*; import android.net.*; import android.webkit.CookieManager;
import java.io.*; import java.net.*; import java.security.*; import java.util.concurrent.ExecutorService;
import org.json.*;
final class DemucsModelManager {
 static final String WIFI_ONLY="demucs_wifi_only"; static final long PERIOD_MS=6L*60*60*1000;
 static boolean networkAvailable(Context c){ConnectivityManager cm=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();if(n==null)return false;NetworkCapabilities cap=cm.getNetworkCapabilities(n);return cap!=null&&cap.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}
 static boolean wifiAllowed(Context c, SharedPreferences p){ boolean only=p.getBoolean(WIFI_ONLY,true); if(!networkAvailable(c))return false; ConnectivityManager cm=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE); NetworkCapabilities cap=cm.getNetworkCapabilities(cm.getActiveNetwork()); return !only||cap.hasTransport(NetworkCapabilities.TRANSPORT_WIFI); }
 static File dir(Context c){File d=new File(c.getFilesDir(),"demucs-models"); d.mkdirs(); return d;}
 static void refresh(Context c, SharedPreferences prefs, ExecutorService io, String base){ if(!wifiAllowed(c,prefs))return; io.submit(()->{try{ URL u=new URL(base+"/api/mobile/demucs-onnx/status"); HttpURLConnection x=(HttpURLConnection)u.openConnection(); String ck=CookieManager.getInstance().getCookie(u.toString()); if(ck!=null)x.setRequestProperty("Cookie",ck); JSONObject root=new JSONObject(new String(x.getInputStream().readAllBytes())); JSONObject models=root.optJSONObject("models"); if(models==null)return; for(String k:models.keySet()){JSONObject m=models.getJSONObject(k); int n=Integer.parseInt(k); String sha=m.getString("sha256"); File f=new File(dir(c),"demucs-"+n+".onnx"); if(f.isFile()&&sha.equalsIgnoreCase(hash(f)))continue; download(c,base+m.getString("url"),f,sha);} prefs.edit().putLong("demucs_last_check",System.currentTimeMillis()).apply();}catch(Exception ignored){}}); }
 static boolean installBundledDefault(Context c,File target){if(target.isFile())return true;try(InputStream in=c.getAssets().open("demucs-default-4.onnx");OutputStream out=new FileOutputStream(target)){in.transferTo(out);return true;}catch(Exception ignored){return false;}}
 static void bootstrap(Context c,SharedPreferences prefs,ExecutorService io,String base){File f=new File(dir(c),"demucs-4.onnx"); if(f.isFile()||installBundledDefault(c,f)||!networkAvailable(c))return; io.submit(()->{try{download(c,base+"/api/mobile/demucs-onnx/bootstrap",f,"");}catch(Exception ignored){}});}
 static void download(Context c,String url,File target,String expected)throws Exception{HttpURLConnection x=(HttpURLConnection)new URL(url).openConnection(); String ck=CookieManager.getInstance().getCookie(url); if(ck!=null)x.setRequestProperty("Cookie",ck); if(x.getResponseCode()/100!=2)throw new IOException("HTTP "+x.getResponseCode()); File tmp=new File(target.getParentFile(),target.getName()+".tmp"); try(InputStream in=x.getInputStream();OutputStream out=new FileOutputStream(tmp)){in.transferTo(out);} if(!expected.isEmpty()&&!expected.equalsIgnoreCase(hash(tmp))){tmp.delete();throw new IOException("SHA-256 mismatch");} if(target.exists())target.delete(); if(!tmp.renameTo(target))throw new IOException("Cannot install model");}
 static String hash(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[]b=new byte[131072];for(int n;(n=in.read(b))>0;)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte b:d.digest())s.append(String.format("%02x",b));return s.toString();}
}