apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mta-audio-editor-data
  namespace: mta-audio-editor
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  # storageClassName: standard
