apiVersion: v1
kind: Service
metadata:
  name: mta-audio-editor
  namespace: mta-audio-editor
spec:
  selector:
    app: mta-audio-editor
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
